import type { ClearProgressCommandHandler } from "../commands/clear-progress.command-handler";
import type { DeleteSavedCatalogFilterCommandHandler } from "../commands/delete-saved-catalog-filter.command-handler";
import type { EnrollCourseCommandHandler } from "../commands/enroll-course.command-handler";
import type { ImportProgressCommandHandler } from "../commands/import-progress.command-handler";
import type { RecordAttemptCommandHandler } from "../commands/record-attempt.command-handler";
import type { RemoveBookmarkCommandHandler } from "../commands/remove-bookmark.command-handler";
import type { SaveAchievementCommandHandler } from "../commands/save-achievement.command-handler";
import type { SaveAttemptCommandHandler } from "../commands/save-attempt.command-handler";
import type { SaveBookmarkCommandHandler } from "../commands/save-bookmark.command-handler";
import type { SaveDailyChallengeCommandHandler } from "../commands/save-daily-challenge.command-handler";
import type { SaveDiagnosisCommandHandler } from "../commands/save-diagnosis.command-handler";
import type { SaveLessonProgressCommandHandler } from "../commands/save-lesson-progress.command-handler";
import type { SavePlanProgressCommandHandler } from "../commands/save-plan-progress.command-handler";
import type { SaveReviewItemCommandHandler } from "../commands/save-review-item.command-handler";
import type { SaveReviewTargetCommandHandler } from "../commands/save-review-target.command-handler";
import type { SaveSavedCatalogFilterCommandHandler } from "../commands/save-saved-catalog-filter.command-handler";
import type { SaveSessionCommandHandler } from "../commands/save-session.command-handler";
import type { SaveSettingCommandHandler } from "../commands/save-setting.command-handler";
import type { SaveStreakCommandHandler } from "../commands/save-streak.command-handler";
import type { SaveTopicMasteryCommandHandler } from "../commands/save-topic-mastery.command-handler";
import type { ExportProgressQueryHandler } from "../queries/export-progress.query-handler";
import type { GetSessionQueryHandler } from "../queries/get-session.query-handler";
import type { GetSettingQueryHandler } from "../queries/get-setting.query-handler";
import type { GetStreakQueryHandler } from "../queries/get-streak.query-handler";
import type { ListAchievementsQueryHandler } from "../queries/list-achievements.query-handler";
import type { ListAttemptsQueryHandler } from "../queries/list-attempts.query-handler";
import type { ListBookmarksQueryHandler } from "../queries/list-bookmarks.query-handler";
import type { ListDailyChallengesQueryHandler } from "../queries/list-daily-challenges.query-handler";
import type { ListDiagnosesQueryHandler } from "../queries/list-diagnoses.query-handler";
import type { ListEnrollmentsQueryHandler } from "../queries/list-enrollments.query-handler";
import type { ListLessonProgressQueryHandler } from "../queries/list-lesson-progress.query-handler";
import type { ListPlanProgressQueryHandler } from "../queries/list-plan-progress.query-handler";
import type { ListReviewItemsQueryHandler } from "../queries/list-review-items.query-handler";
import type { ListReviewTargetsQueryHandler } from "../queries/list-review-targets.query-handler";
import type { ListSavedCatalogFiltersQueryHandler } from "../queries/list-saved-catalog-filters.query-handler";
import type { ListStudySessionsQueryHandler } from "../queries/list-study-sessions.query-handler";
import type { ListTopicMasteryQueryHandler } from "../queries/list-topic-mastery.query-handler";

export type ProgressServices = {
  listAttempts: ListAttemptsQueryHandler;
  recordAttempt: RecordAttemptCommandHandler;
  saveAttempt: SaveAttemptCommandHandler;
  saveSession: SaveSessionCommandHandler;
  getSession: GetSessionQueryHandler;
  saveSetting: SaveSettingCommandHandler;
  getSetting: GetSettingQueryHandler;
  clearProgress: ClearProgressCommandHandler;
  enrollCourse: EnrollCourseCommandHandler;
  exportProgress: ExportProgressQueryHandler;
  importProgress: ImportProgressCommandHandler;
  listEnrollments: ListEnrollmentsQueryHandler;
  saveLessonProgress: SaveLessonProgressCommandHandler;
  listLessonProgress: ListLessonProgressQueryHandler;
  savePlanProgress: SavePlanProgressCommandHandler;
  listPlanProgress: ListPlanProgressQueryHandler;
  saveBookmark: SaveBookmarkCommandHandler;
  removeBookmark: RemoveBookmarkCommandHandler;
  listBookmarks: ListBookmarksQueryHandler;
  saveReviewItem: SaveReviewItemCommandHandler;
  listReviewItems: ListReviewItemsQueryHandler;
  saveReviewTarget: SaveReviewTargetCommandHandler;
  listReviewTargets: ListReviewTargetsQueryHandler;
  listStudySessions: ListStudySessionsQueryHandler;
  saveDiagnosis: SaveDiagnosisCommandHandler;
  listDiagnoses: ListDiagnosesQueryHandler;
  saveDailyChallenge: SaveDailyChallengeCommandHandler;
  listDailyChallenges: ListDailyChallengesQueryHandler;
  saveStreak: SaveStreakCommandHandler;
  saveTopicMastery: SaveTopicMasteryCommandHandler;
  getStreak: GetStreakQueryHandler;
  saveAchievement: SaveAchievementCommandHandler;
  listAchievements: ListAchievementsQueryHandler;
  listTopicMastery: ListTopicMasteryQueryHandler;
  listSavedCatalogFilters: ListSavedCatalogFiltersQueryHandler;
  saveSavedCatalogFilter: SaveSavedCatalogFilterCommandHandler;
  deleteSavedCatalogFilter: DeleteSavedCatalogFilterCommandHandler;
};
