packages:
  - "packages/*"

allowBuilds:
  '@ast-grep/cli': set this to true or false
  core-js-pure: set this to true or false
  dtrace-provider: set this to true or false
  protobufjs: set this to true or false
  re2: set this to true or false
