import type { AchievementDefinitionsPort } from "./ports/achievement-definitions-port.port";
import type { ActionForDiagnosisPort } from "./ports/action-for-diagnosis-port.port";
import type { AddStudyPointsPort } from "./ports/add-study-points-port.port";
import type { BuildKnowledgeGraphPort } from "./ports/build-knowledge-graph-port.port";
import type { CalculateTopicMasteryPort } from "./ports/calculate-topic-mastery-port.port";
import type { ClearProgressPort } from "./ports/clear-progress-port.port";
import type { ClockPort } from "./ports/clock-port.port";
import type { EnrollCoursePort } from "./ports/enroll-course-port.port";
import type { ExportProgressPort } from "./ports/export-progress-port.port";
import type { GetAssessmentPort } from "./ports/get-assessment-port.port";
import type { GetCatalogPort } from "./ports/get-catalog-port.port";
import type { GetCoursePort } from "./ports/get-course-port.port";
import type { GetLessonPort } from "./ports/get-lesson-port.port";
import type { GetQuestionPort } from "./ports/get-question-port.port";
import type { GetSessionPort } from "./ports/get-session-port.port";
import type { GetSettingPort } from "./ports/get-setting-port.port";
import type { GetStreakPort } from "./ports/get-streak-port.port";
import type { GetStudyPlanPort } from "./ports/get-study-plan-port.port";
import type { GetTopicMapPort } from "./ports/get-topic-map-port.port";
import type { GetTopicPort } from "./ports/get-topic-port.port";
import type { IdPort } from "./ports/id-port.port";
import type { ImportProgressPort } from "./ports/import-progress-port.port";
import type { ListAchievementsPort } from "./ports/list-achievements-port.port";
import type { ListAttemptsPort } from "./ports/list-attempts-port.port";
import type { ListBookmarksPort } from "./ports/list-bookmarks-port.port";
import type { ListDailyChallengesPort } from "./ports/list-daily-challenges-port.port";
import type { ListDiagnosesPort } from "./ports/list-diagnoses-port.port";
import type { ListEnrollmentsPort } from "./ports/list-enrollments-port.port";
import type { ListLessonProgressPort } from "./ports/list-lesson-progress-port.port";
import type { ListPlanProgressPort } from "./ports/list-plan-progress-port.port";
import type { ListReviewItemsPort } from "./ports/list-review-items-port.port";
import type { ListReviewTargetsPort } from "./ports/list-review-targets-port.port";
import type { ListStudySessionsPort } from "./ports/list-study-sessions-port.port";
import type { ListTopicMasteryPort } from "./ports/list-topic-mastery-port.port";
import type { ParseEditorialBlocksPort } from "./ports/parse-editorial-blocks-port.port";
import type { PreviewReviewPort } from "./ports/preview-review-port.port";
import type { RecommendNextPort } from "./ports/recommend-next-port.port";
import type { RecordAttemptPort } from "./ports/record-attempt-port.port";
import type { RecordStudyActivityPort } from "./ports/record-study-activity-port.port";
import type { SaveAchievementPort } from "./ports/save-achievement-port.port";
import type { SaveAttemptPort } from "./ports/save-attempt-port.port";
import type { SaveBookmarkPort } from "./ports/save-bookmark-port.port";
import type { SaveDailyChallengePort } from "./ports/save-daily-challenge-port.port";
import type { SaveDiagnosisPort } from "./ports/save-diagnosis-port.port";
import type { SaveLessonProgressPort } from "./ports/save-lesson-progress-port.port";
import type { SavePlanProgressPort } from "./ports/save-plan-progress-port.port";
import type { SaveReviewItemPort } from "./ports/save-review-item-port.port";
import type { SaveReviewTargetPort } from "./ports/save-review-target-port.port";
import type { SaveSessionPort } from "./ports/save-session-port.port";
import type { SaveSettingPort } from "./ports/save-setting-port.port";
import type { SaveStreakPort } from "./ports/save-streak-port.port";
import type { SaveTopicMasteryPort } from "./ports/save-topic-mastery-port.port";
import type { ScheduleReviewPort } from "./ports/schedule-review-port.port";
import type { SuggestDiagnosisPort } from "./ports/suggest-diagnosis-port.port";
import type { SyncAchievementsPort } from "./ports/sync-achievements-port.port";

export interface ApplicationPorts {
  getCatalog: GetCatalogPort;
  getCourse: GetCoursePort;
  getLesson: GetLessonPort;
  getQuestion: GetQuestionPort;
  getAssessment: GetAssessmentPort;
  getTopicMap: GetTopicMapPort;
  getTopic: GetTopicPort;
  getStudyPlan: GetStudyPlanPort;
  listAttempts: ListAttemptsPort;
  recordAttempt: RecordAttemptPort;
  saveAttempt: SaveAttemptPort;
  saveSession: SaveSessionPort;
  getSession: GetSessionPort;
  saveSetting: SaveSettingPort;
  getSetting: GetSettingPort;
  clearProgress: ClearProgressPort;
  enrollCourse: EnrollCoursePort;
  exportProgress: ExportProgressPort;
  importProgress: ImportProgressPort;
  listEnrollments: ListEnrollmentsPort;
  saveLessonProgress: SaveLessonProgressPort;
  listLessonProgress: ListLessonProgressPort;
  savePlanProgress: SavePlanProgressPort;
  listPlanProgress: ListPlanProgressPort;
  saveBookmark: SaveBookmarkPort;
  listBookmarks: ListBookmarksPort;
  saveReviewItem: SaveReviewItemPort;
  listReviewItems: ListReviewItemsPort;
  saveReviewTarget: SaveReviewTargetPort;
  listReviewTargets: ListReviewTargetsPort;
  listStudySessions: ListStudySessionsPort;
  saveDiagnosis: SaveDiagnosisPort;
  listDiagnoses: ListDiagnosesPort;
  saveDailyChallenge: SaveDailyChallengePort;
  listDailyChallenges: ListDailyChallengesPort;
  saveStreak: SaveStreakPort;
  saveTopicMastery: SaveTopicMasteryPort;
  getStreak: GetStreakPort;
  saveAchievement: SaveAchievementPort;
  listAchievements: ListAchievementsPort;
  listTopicMastery: ListTopicMasteryPort;
  scheduleReview: ScheduleReviewPort;
  previewReview: PreviewReviewPort;
  recordStudyActivity: RecordStudyActivityPort;
  calculateTopicMastery: CalculateTopicMasteryPort;
  suggestDiagnosis: SuggestDiagnosisPort;
  actionForDiagnosis: ActionForDiagnosisPort;
  recommendNext: RecommendNextPort;
  achievementDefinitions: AchievementDefinitionsPort;
  syncAchievements: SyncAchievementsPort;
  addStudyPoints: AddStudyPointsPort;
  clock: ClockPort;
  ids: IdPort;
  parseEditorialBlocks: ParseEditorialBlocksPort;
  buildKnowledgeGraph: BuildKnowledgeGraphPort;
}
