import { extname, join, relative } from "@std/path";

type FilePolicy = {
  allow: (comment: string) => boolean;
  markers: string[];
};

const root = Deno.cwd();

const failures: string[] = [];

const policies = new Map<string, FilePolicy>([
  [
    "Dockerfile",
    {
      markers: ["#"],
      allow: (comment) =>
        comment === "# syntax=docker/dockerfile:1.10" || comment.startsWith("# renovate:"),
    },
  ],
  ["justfile", { markers: ["#"], allow: (comment) => comment.startsWith("#!") }],
]);

const extensionPolicies = new Map<string, FilePolicy>([
  [".js", { markers: ["//", "/*"], allow: () => false }],
  [".jsx", { markers: ["//", "/*"], allow: () => false }],
  [".mjs", { markers: ["//", "/*"], allow: () => false }],
  [".cjs", { markers: ["//", "/*"], allow: () => false }],
  [".ts", { markers: ["//", "/*"], allow: () => false }],
  [".tsx", { markers: ["//", "/*"], allow: () => false }],
  [".hcl", { markers: ["#", "//", "/*"], allow: () => false }],
  [".jsonc", { markers: ["//", "/*"], allow: () => false }],
  [".md", { markers: ["<!--", "/*"], allow: () => false }],
  [".sql", { markers: ["--"], allow: (comment) => /^-- migrate:(?:up|down)$/.test(comment) }],
  [
    ".toml",
    {
      markers: ["#"],
      allow: (comment) =>
        comment.startsWith("# @generated - this file is auto-generated by `mise lock`"),
    },
  ],
]);

export function commentAt(line: string, markers: string[]): number {
  let quote = "";

  let escaped = false;

  for (let index = 0; index < line.length; index += 1) {
    const character = line[index];

    if (quote !== "") {
      if (escaped) {
        escaped = false;
      } else if (character === "\\") {
        escaped = true;
      } else if (character === quote) {
        quote = "";
      }

      continue;
    }

    if (character === String.fromCharCode(34) || character === "'" || character === "`") {
      quote = character;

      continue;
    }

    const marker = markers.find((candidate) => line.startsWith(candidate, index));

    if (marker !== undefined) {
      if (marker === "//" && line[index - 1] === "\\") {
        continue;
      }

      return index;
    }
  }

  return -1;
}

export function policyFor(path: string): FilePolicy | undefined {
  const name = path.split("/").at(-1) ?? path;

  return policies.get(name) ?? extensionPolicies.get(extname(name));
}

export async function inspectFile(path: string, policy: FilePolicy): Promise<void> {
  const content = await Deno.readTextFile(path);

  let blockComment = false;

  for (const [lineIndex, line] of content.split("\n").entries()) {
    if (blockComment) {
      if (line.includes("*/")) {
        blockComment = false;
      }

      continue;
    }

    if (policy.markers.includes("/*")) {
      const blockStart = commentAt(line, ["/*"]);

      if (blockStart >= 0) {
        if (!line.includes("*/", blockStart + 2)) {
          blockComment = true;
        }

        failures.push(`${relative(root, path)}:${lineIndex + 1}: comentário não permitido`);

        continue;
      }
    }

    const index = commentAt(
      line,
      policy.markers.filter((marker) => marker !== "/*"),
    );

    if (index < 0) {
      continue;
    }

    const comment = line.slice(index).trim();

    if (!policy.allow(comment)) {
      failures.push(`${relative(root, path)}:${lineIndex + 1}: comentário não permitido`);
    }
  }
}

export async function walk(directory: string): Promise<void> {
  for await (const entry of Deno.readDir(directory)) {
    if ([".git", ".cache", "dist", "node_modules"].includes(entry.name)) {
      continue;
    }

    const path = join(directory, entry.name);

    if (entry.isDirectory) {
      await walk(path);

      continue;
    }

    const policy = policyFor(relative(root, path));

    if (policy !== undefined) {
      await inspectFile(path, policy);
    }
  }
}

await walk(root);

if (failures.length > 0) {
  console.error("Política de comentários inválida:");

  for (const failure of failures) {
    console.error(`- ${failure}`);
  }

  Deno.exit(1);
}

console.log("Política de comentários válida: nenhum comentário narrativo encontrado.");
