import type { ApplicationPorts } from "@guesant/saberes-application";

export type ProgressWritePorts = Pick<
  ApplicationPorts,
  | "classifyStudyCapture"
  | "completeStudyCapture"
  | "postponeStudyCapture"
  | "archiveStudyCapture"
  | "restoreStudyCapture"
  | "undoStudyCapture"
  | "createCalendarEntry"
  | "createPersonalRelation"
  | "archivePersonalRelation"
  | "restorePersonalRelation"
  | "recordAttempt"
  | "saveAttempt"
  | "saveSession"
  | "saveSetting"
  | "clearProgress"
  | "enrollCourse"
  | "importProgress"
  | "saveLessonProgress"
  | "savePlanProgress"
  | "saveSavedCatalogFilter"
  | "deleteSavedCatalogFilter"
  | "saveBookmark"
  | "removeBookmark"
  | "saveReviewItem"
  | "saveReviewTarget"
  | "saveDiagnosis"
  | "saveDailyChallenge"
  | "saveFocusSession"
  | "saveStreak"
  | "saveStudyGoal"
  | "savePersonalWorkspace"
  | "saveAchievement"
  | "saveAcademicDiscipline"
  | "deleteAcademicDiscipline"
  | "saveTopicMastery"
>;
