export const cssBaselineConfig = {
  "*, *::before, *::after": {
    boxSizing: "border-box",
    gap: 0,
    margin: 0,
    outline: 0,
    padding: 0,
    fontSize: "inherit",
    fontWeight: "inherit",
    lineHeight: "inherit",
  },
  "html, body, #root": {
    minHeight: "100%",
    fontFamily: "Roboto Slab, Georgia, serif",
    fontSize: "1rem",
    fontWeight: 400,
    lineHeight: 1.5,
  },
  "button, input, optgroup, select, textarea": { fontFamily: "inherit" },
  "button, input, select, textarea": { letterSpacing: "inherit" },
  "h1, h2, h3, h4, h5, h6": { fontWeight: 700, lineHeight: 1.25 },
  "strong, b": { fontWeight: 700 },
  "code, kbd, pre, samp": { fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace" },
  h1: { fontSize: "2rem" },
  h2: { fontSize: "1.5rem" },
  h3: { fontSize: "1.25rem" },
  h4: { fontSize: "1.125rem" },
  h5: { fontSize: "1.125rem" },
  h6: { fontSize: "1rem" },
  "a, button, input, select, textarea": { color: "inherit", font: "inherit", lineHeight: "inherit" },
  "a, button": { textDecoration: "none" },
  button: { appearance: "none", background: "transparent", border: 0, cursor: "pointer", letterSpacing: "inherit" },
  "input, select, textarea": { letterSpacing: "inherit" },
  "img, picture, video, canvas, svg": { display: "block", maxWidth: "100%" },
  "[hidden]": { display: "none !important" },
  "*:focus-visible": {
    outline: "3px solid var(--mui-palette-primary-main)",
    outlineOffset: "2px",
  },
};
