name: OpenSSF Scorecard

on:
  workflow_dispatch:
  schedule:
    - cron: "17 4 * * 1"

permissions: read-all

jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      issues: read
      pull-requests: read
      checks: read
      security-events: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false

      - name: Executar análise
        uses: ossf/scorecard-action@2d1146689b8cda280b9bc96326124645441f03bc
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: Publicar artefato SARIF
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08
        with:
          name: scorecard-results
          path: results.sarif
          retention-days: 5

      - name: Publicar no Code Scanning
        uses: github/codeql-action/upload-sarif@f205ea1c3313d32999d8d6a48b4f6530d4437b38
        with:
          sarif_file: results.sarif
